### ISSUE TITLE
UMT-VIT module

### ISSUE THREAD

**Issue by JackeyZhang1001** [OpenGVLab/unmasked_teacher#36]
I want to load vit module only, how can I load it from pertained?

**Comment by Andy1621** [comment]
You can simply download the model weights from [here](https://github.com/OpenGVLab/unmasked_teacher/blob/main/single_modality/MODEL_ZOO.md#pretraining) and use ViT module.

**Comment by JackeyZhang1001** [comment]
I download the model weights, but I don't know how to init the model that I can load the state_dict, could you please give me a demo?

**Comment by Andy1621** [comment]
You can simply use the model code [here](https://github.com/OpenGVLab/unmasked_teacher/blob/main/single_modality/models/modeling_finetune.py) and load the model. For a demo, you can follow those use in [VideoMAE](https://github.com/MCG-NJU/VideoMAE?tab=readme-ov-file), since we share the same model code.
